/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier for this Paddle webhook alert. Integer value sent as a string.
 */
export type AlertID = string;
/**
 * The three letter ISO currency code of the vendor’s default currency at the time of the transaction. Eg: `USD`, `GBP`.
 */
export type BalanceCurrency = string;
/**
 * The checkout id of the order created.
 */
export type CheckoutID = string;
/**
 * The two-letter ISO country code of the customer. Eg: `US`, `GB`. See [Supported Countries](/reference/platform-parameters/supported-countries).
 */
export type Country = string;
/**
 * The coupon code that was used on this order
 */
export type Coupon = string;
/**
 * The three-letter ISO currency code. Eg: `USD`, `GBP`. See [Supported Currencies](/reference/platform-parameters/supported-currencies).
 */
export type Currency = string;
/**
 * The name of the customer. For card payments, this will return the cardholder name entered by the buyer during the checkout. For PayPal payments, this will return the name from the PayPal account used during the checkout. For all other payment methods where the name is not collected (including Apple Pay and Wire Transfer), this will be empty.
 */
export type CustomerName = string;
/**
 * The email address of the customer.
 */
export type Email = string;
/**
 * The date and time the event was triggered in UTC (Coordinated Universal Time).
 */
export type EventTime = string;
/**
 * The value of this field `0` or `1` indicates whether the user has agreed to receive marketing messages from the vendor.
 */
export type MarketingConsent = 0 | 1;
/**
 * The Paddle Order ID for this payment. This can be used to look up the order within your Seller Dashboard.
 */
export type OrderID = string;
/**
 * This field contains any values that you passed into the checkout using the `passthrough` parameter. See the [Pass Parameters documentation](/guides/how-tos/checkout/pass-parameters#sending-additional-user-data) for more information.
 */
export type Passthrough = string;
/**
 * Payment method used to make the transaction.
 */
export type PaymentMethod = "card" | "paypal" | "free" | "apple-pay" | "wire-transfer";
/**
 * The dashboard ID of the product purchased in this order.
 */
export type ProductID = string;
/**
 * The number of products or subscription seats sold in the transaction.
 */
export type Quantity = string;
/**
 * This field contains an encrypted token that you can use to verify the request authenticity. See [Verifying Webhooks](/webhook-reference/verifying-webhooks).
 */
export type PSignature = string;

/**
 * Identify this event with the HTTP POST parameter `alert_name` with a value of `payment_succeeded`
 */
export interface PaymentSucceeded {
  alert_name?: string;
  alert_id?: AlertID;
  balance_currency?: BalanceCurrency;
  /**
   * The amount of revenue added to the vendor’s balance as a result of this payment, in the vendor’s `balance_currency` at the time of the transaction.
   */
  balance_earnings?: string;
  /**
   * The fee amount taken from the vendor, in the vendor’s `balance_currency` at the time of the transaction.
   */
  balance_fee?: string;
  /**
   * The total amount received from the customer as a result of the payment, in the vendor’s `balance_currency` at the time of the transaction.
   */
  balance_gross?: string;
  /**
   * The amount of tax received from the customer, in the vendor’s `balance_currency` at the time of the transaction.
   */
  balance_tax?: string;
  checkout_id?: CheckoutID;
  country?: Country;
  coupon?: Coupon;
  currency?: Currency;
  customer_name?: CustomerName;
  /**
   * The amount of this payment that was credited to your balance.
   */
  earnings?: string;
  email?: Email;
  event_time?: EventTime;
  /**
   * The fee taken by Paddle for this payment.
   */
  fee?: string;
  /**
   * This field is deprecated and will be removed in a future update.
   */
  ip?: string;
  marketing_consent?: MarketingConsent;
  order_id?: OrderID;
  passthrough?: Passthrough;
  payment_method?: PaymentMethod;
  /**
   * The amount of this payment that was paid in tax/VAT.
   */
  payment_tax?: string;
  product_id?: ProductID;
  /**
   * The name of the product included in the transaction.
   */
  product_name?: string;
  quantity?: Quantity;
  /**
   * A URL where the receipt for the transaction can be retrieved.
   */
  receipt_url?: string;
  /**
   * The total value of the sale (including tax) in the sale currency.
   */
  sale_gross?: string;
  /**
   * Whether the dashboard price was overridden.
   */
  used_price_override?: true | false;
  p_signature?: PSignature;
  [k: string]: unknown;
}
