/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The unique identifier for this Paddle webhook alert. Integer value sent as a string.
 */
export type AlertID = string;
/**
 * A URL of the 'Cancel Subscription' page. [See this documentation](/guides/how-tos/subscriptions/cancel-and-pause#cancel-subscription-url) on cancelation URLs. You should store this URL along with the subscribed customer in your database.
 */
export type CancelURL = string;
/**
 * The checkout id of the order created.
 */
export type CheckoutID = string;
/**
 * The three-letter ISO currency code. Eg: `USD`, `GBP`. See [Supported Currencies](/reference/platform-parameters/supported-currencies).
 */
export type Currency = string;
/**
 * The email address of the customer.
 */
export type Email = string;
/**
 * The date and time the event was triggered in UTC (Coordinated Universal Time).
 */
export type EventTime = string;
/**
 * The value of this field `0` or `1` indicates whether the user has agreed to receive marketing messages from the vendor.
 */
export type MarketingConsent = 0 | 1;
/**
 * This field contains any values that you passed into the checkout using the `passthrough` parameter. See the [Pass Parameters documentation](/guides/how-tos/checkout/pass-parameters#sending-additional-user-data) for more information.
 */
export type Passthrough = string;
/**
 * The number of products or subscription seats sold in the transaction.
 */
export type Quantity = string;
/**
 * This is the current status of the subscription. A list of possible values and their meanings can be found under [Event Statuses](/reference/platform-parameters/event-statuses).
 */
export type Status = "active" | "trialing" | "past_due" | "paused" | "deleted";
/**
 * This is the unique Subscription ID for this customer’s subscription. You should store this with the customer in your database, as it is needed for making API calls.
 */
export type SubscriptionID = string;
/**
 * The ID of the Subscription Plan the customer is subscribed to. (This is the value that will change upon plan change).
 */
export type SubscriptionPlanID = string;
/**
 * The price per unit of the subscription.
 */
export type UnitPrice = string;
/**
 * A URL of the ‘Update Payment Details’ page. [See this documentation](/guides/how-tos/subscriptions/update-payment-details#update-payment-details-url) on update URLs. You should store this URL along with the subscribed customer in your database.
 */
export type UpdateURL = string;
/**
 * The unique ID of the subscription payment.
 */
export type SubscriptionPaymentID = string;
/**
 * Number of payments made to date, starting from `1` for the customer's first payment. Integer sent as string.
 */
export type Instalments = string;
/**
 * The Paddle Order ID for this payment. This can be used to look up the order within your Seller Dashboard.
 */
export type OrderID = string;
/**
 * The customer user id.
 */
export type UserID = string;
/**
 * This field contains an encrypted token that you can use to verify the request authenticity. See [Verifying Webhooks](/webhook-reference/verifying-webhooks).
 */
export type PSignature = string;

/**
 * Identify this event with the HTTP POST parameter `alert_name` with a value of `subscription_payment_failed`
 */
export interface SubscriptionPaymentFailed {
  alert_name?: string;
  alert_id?: AlertID;
  /**
   * The amount that we tried to charge for this payment. Decimal value sent as a string.
   */
  amount?: string;
  cancel_url?: CancelURL;
  checkout_id?: CheckoutID;
  currency?: Currency;
  email?: Email;
  event_time?: EventTime;
  marketing_consent?: MarketingConsent;
  /**
   * The date that we will next try to process this failed payment.
   */
  next_retry_date?: string;
  passthrough?: Passthrough;
  quantity?: Quantity;
  status?: Status;
  subscription_id?: SubscriptionID;
  subscription_plan_id?: SubscriptionPlanID;
  unit_price?: UnitPrice;
  update_url?: UpdateURL;
  subscription_payment_id?: SubscriptionPaymentID;
  instalments?: Instalments;
  order_id?: OrderID;
  user_id?: UserID;
  /**
   * Number of failed payment attempts made so far for this instalment. This number will reset back to 1 if the “Reset Attempts” button in the subscription management page is clicked.
   */
  attempt_number?: string;
  p_signature?: PSignature;
  [k: string]: unknown;
}
